<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DHRSJC00SM0029" name="com.pid.qa.usermgmt.CRUD_UserGroupResource" tests="112" failures="14" timestamp="24 Jun 2020 17:22:33 GMT" time="116.550" errors="0">
  <testcase name="userGroupResourceTest" time="1.179" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.000" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.212" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.207" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.191" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.130" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.181" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.242" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.218" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.194" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.165" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.167" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.099" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.184" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:110)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.285" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.142" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:155)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.196" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.250" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.198" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.167" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.113" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.222" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.253" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.451" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.211" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.209" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.272" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.202" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.164" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.144" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.216" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.159" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.192" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.197" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.140" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.208" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.154" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.133" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.152" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.002" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.156" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.149" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.191" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:122)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.151" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.146" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.131" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.199" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.183" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.195" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;401&gt; but was:&lt;403&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<401> but was:<403>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:82)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.241" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.213" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.139" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.004" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.199" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;401&gt; but was:&lt;200&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<401> but was:<200>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:82)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.236" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.308" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.140" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.148" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.172" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.150" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.225" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.159" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.209" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;200&gt; but was:&lt;401&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<401>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:116)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.160" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.210" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.182" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.167" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.151" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.241" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.202" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.231" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.217" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:142)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.124" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.141" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.175" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.144" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.144" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.158" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.203" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.133" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.192" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.159" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.245" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.123" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.244" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.135" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.146" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.203" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.154" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM407]&gt; but was:&lt;[UM501]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM407]> but was:<[UM501]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.234" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.189" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.138" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource">
    <failure type="junit.framework.AssertionFailedError" message="expected:&lt;[UM505, UM202, UM506]&gt; but was:&lt;[UM506, UM505, UM202]&gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<[UM505, UM202, UM506]> but was:<[UM506, UM505, UM202]>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:74)
at com.pid.qa.usermgmt.CRUD_UserGroupResource.userGroupResourceTest(CRUD_UserGroupResource.java:87)
at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- userGroupResourceTest -->
  <testcase name="userGroupResourceTest" time="1.285" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.206" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.257" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.265" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.251" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.211" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.001" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="0.000" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.177" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.197" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
  <testcase name="userGroupResourceTest" time="1.101" classname="com.pid.qa.usermgmt.CRUD_UserGroupResource"/>
</testsuite> <!-- com.pid.qa.usermgmt.CRUD_UserGroupResource -->
